# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in jekyll-m_tool.gemspec
gemspec

gem "rake", "~> 13.0"
gem 'debase', '~> 0.2.4.1'
gem 'ruby-debug-ide', '~> 0.7.2'

gem "rubocop", "~> 1.7"
